// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }



  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4d1-U1B6zuVIfP7Ppl4FFMYYPEk7x2og',
    appId: '1:952562712156:android:a8884c8ec4b7ded681b099',
    messagingSenderId: '952562712156',
    projectId: 'lira-app-5eb5e',
    storageBucket: 'lira-app-5eb5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV5LMF8SaRlBonqG1YnGWD3uqmR3yeScg',
    appId: '1:952562712156:ios:2a17b1a47303344381b099',
    messagingSenderId: '952562712156',
    projectId: 'lira-app-5eb5e',
    storageBucket: 'lira-app-5eb5e.appspot.com',
    iosBundleId: 'com.example.test',
  );

}